ktor {
    deployment {
        port = 8080
        # Cloud Run inyecta el puerto en PORT (ADR-10).
        port = ${?PORT}
    }
    application {
        modules = [ co.edu.uniquindio.exploracity.ApplicationKt.module ]
    }
}
